Feature/autocomplete
MissouriMRR/propguard pull request #20
Opened 2019-12-18 00:19 UTC by translucentleaf

@henrievjen made the text editor component as well as the suggestion feature.

I just redid the CSS for the project for the new design and added the navbar in.

Maybe in the future we'll actually make this autocomplete feature but I'm concerned with the pace of the project so I'd rather get the essential stuff pumped out. This includes getting the tutorial display component working (that shows the step-by-step instructions) and getting the drone simulator working.

I'll also deal with the merge conflicts.

2020-01-08 05:02 UTC, ClayMav requested changes

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +Propguard is a webapp built for Missouri S&T's Multirotor Drone Design Team meant to preserve the knowledge and experience of its past members. This means that Propguard teaches new members how to st
```suggestion
Propguard is a web app built for Missouri S&T's Multirotor Robot Design Team meant to preserve the knowledge and experience of its past members. Propguard teaches new members how to start working on the team's flight code via a Codeacademy-like tutorial interface.
```

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +A second part of Propguard (in development) is to create a wiki that will serve as the collective knowledge of all the past members of the Multirotor team. During our flight tests we always run into
```suggestion
It includes a wiki that will serve as the collective knowledge of all the past members of the team. During our flight tests we always run into issues, and some of those issues happen to be things that have been solved in the past. We obviously don't want to keep making the same mistakes.
```

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +yarn
Be explicit when writing instructions, this works but explicit is better
```suggestion
yarn install
```

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +### Winter Break Goals
Give dates

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +### Before Spring Break
Give dates

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +### Before Finals
Give dates

2020-01-08 05:02 UTC, ClayMav commented on README.md
> +### Summer 2020 Before Competition
Give dates

2020-01-08 05:02 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +          A webapp that teaches people how to use Dronekit and Python to start
```suggestion
          A webapp that teaches people how to use MAVSDK and Python to start
```

2020-01-08 05:02 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +          and launch the drones
```suggestion
          flying copters autonomously
```

2020-01-08 05:02 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +    const terminal: any = document.getElementById("terminal");
Is there a reason we are getting this by id and not just making it

2020-01-30 21:02 UTC, translucentleaf commented
Alright I updated the roadmaps to reflect the stuff that we've talked about @ClayMav and I removed some of the redundant DOM code for the autocomplete feature. Please review the changes I made.

2020-01-31 16:46 UTC, ClayMav requested changes
Sorry I didn't catch all this earlier. This review was much more in depth than before.

Here is a link about semantic elements: https://www.w3schools.com/html/html5_semantic_elements.asp

2020-01-31 16:46 UTC, ClayMav commented on .eslintrc.js
> +    "react/jsx-curly-newline": 0,
kinda looks like the auto-formatter wasn't run on this, since this line has double quotes and the one before is single quotes

2020-01-31 16:46 UTC, ClayMav commented on README.md
> +    <p align="center">Currently only two software members really know how to start the drone and enable its autonomous features. We need to change that. Propguard is a webapp that teaches people how
On reevaluation, lets ditch the "two software members" and just keep a version of the last sentence. It's too specific and won't be true all the time.

2020-01-31 16:46 UTC, ClayMav commented on README.md
> +We're working on getting a live version up so for now you'll have to run this project locally on your machine. See the **Get Started** section for instructions on how to run it.
You use use header links to link down to get started

2020-01-31 16:46 UTC, ClayMav commented on README.md
> +- Come up with a system that lets the wiki by easily editable with some CMS like Ghost+Gatsby or something similar (April 14)
Is this still accurate

2020-01-31 16:46 UTC, ClayMav commented on README.md
> +- Come up with a system that lets the wiki by easily editable with some CMS like Ghost+Gatsby or something similar (April 14)
Not sure that the roadmap should be in the repo anyways, you could do it by using projects and issues in github

2020-01-31 16:46 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +const Title: AnyStyledComponent = styled.div`
Is there a reason you switched away from a semantic HTML element to a div

2020-01-31 16:46 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +const Subtext: AnyStyledComponent = styled.span`
is there a reason to use a non-semantic html element instead of a semantic one

2020-01-31 16:46 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +const Main: AnyStyledComponent = styled.div`
if this is truly the main you would think you would use the semantic element

2020-01-31 16:46 UTC, ClayMav commented on src/App.tsx
> +const Main: AnyStyledComponent = styled.div`
if this is truly the main you would think you would use the semantic element

2020-01-31 16:46 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +const Main: AnyStyledComponent = styled.div`
but i don't think this is actually main, so you might consider changing the title

2020-01-31 16:46 UTC, ClayMav commented on src/components/navbar/Navbar.tsx
> +const NavWrapper: AnyStyledComponent = styled.div`
consider adding a "nav" html semantic element somewhere

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +const Main: AnyStyledComponent = styled.div`
maybe stop using the word "Main" for all of your components

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +const Terminal: AnyStyledComponent = styled.form`
does there need to be a form around the text element, since you are controlling it with react it shouldn't be strictly necessary

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +    let text: string = event.target.value;
I would prefer you control the react component and have the value in state

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +    let text: string = event.target.value;
https://reactjs.org/docs/forms.html scroll to "The textarea Tag"

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +        text.length !== 0
make this the first condition of the if statement

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +    let text: string = event.target.value;
Basically just have the onchange be a function that simple updates the state and then do a useeffect hook to check for autocomplete

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +        onSubmit={(event: React.FormEvent<HTMLFormElement>): void =>
would prefer if it was just `onSubmit={handleSubmit}`

2020-01-31 16:46 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +          onChange={(event: React.ChangeEvent<HTMLInputElement>): void => {
If you control it properly you would just have `onChange={handleChange}` or something like that

2020-01-31 16:46 UTC, ClayMav commented on src/components/tutorial-app/TutorialApp.tsx
> +const TutorialPage: AnyStyledComponent = styled.main`
Should this be a main?

2020-01-31 16:46 UTC, ClayMav commented on src/components/tutorial-app/TutorialApp.tsx
> +const Parent: AnyStyledComponent = styled.div`
Bad name

2020-01-31 16:46 UTC, ClayMav commented on src/components/tutorial-display/TutorialDisplay.tsx
> +const TutorialText: AnyStyledComponent = styled.div`
Shouldn't this be a semantic element

2020-02-02 04:51 UTC, translucentleaf commented
Alright you definitely made me think about semantic elements which I kinda forget as I was focusing more on pumping out react components.

2020-02-04 23:32 UTC, ClayMav requested changes

2020-02-04 23:32 UTC, ClayMav commented on README.md
> +    <p align="center">Propguard is a webapp that teaches people how to start writing basic flight code with technologies like Dronekit, MAVSDK, and Python.</p>
```suggestion
    <p align="center">Propguard is a webapp that teaches people how to start writing basic flight code with technologies like PX4, MAVSDK, and Python.</p>
```

2020-02-04 23:32 UTC, ClayMav commented on src/components/landing/Landing.tsx
> +const Subtext: AnyStyledComponent = styled.aside`
```suggestion
const Subtext: AnyStyledComponent = styled.p`
```

2020-02-04 23:32 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +const Terminal: AnyStyledComponent = styled.div`
consider squashing this element

2020-02-04 23:32 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +      if (userInput.length <= cursorPos) {
use `text` instead of `userInput`

2020-02-04 23:32 UTC, ClayMav commented on src/components/text-editor/TextEditor.tsx
> +  });
```suggestion
  }, [userInput, cursorPos]);
```

2020-02-04 23:57 UTC, ClayMav approved these changes

2020-02-05 00:33 UTC, merged