Merging feature/output into master
MissouriMRR/propguard pull request #43
Opened 2020-05-26 18:19 UTC by tomdng

Finally got the drone output and basic error detection working! This feature took a bit longer than usual because it required that a lot of the other stuff was working first (like the text editor, tutorial selection, and etc).

Henri built out the basic shell of the output back when Propguard was a really small project and then I went and fleshed it out a lot more including adding all the logic into it once we redesigned the entire interface.

Resolves features #4 and #14 .

2020-05-31 23:02 UTC, ClayMav requested changes
On windows, this tool doesn't work properly due to the carriage return, or maybe something else. Newlines and spacing should not play much a role if any.
The right column expands horizontally creating a scrollbar when the output line goes past a certain length, this should not happen.
Also the listed altitude does not match the altitude of the code or the "output", same for velocity.
The hint button currently seems confusing in terms of its functionality

2020-05-31 23:02 UTC, ClayMav commented on src/components/navbar/index.tsx
> +    }
Will these two values always bee opposites?

2020-05-31 23:02 UTC, ClayMav commented on src/components/navbar/index.tsx
> +      <NavLogo to="/" onClick={(): void => toggleDisplay(false)}>
lambdas are slow in react renders, statically define this as a function

2020-05-31 23:02 UTC, ClayMav commented on src/components/navbar/index.tsx
> +        onClick={(): void => toggleDisplay(true)}
onClick lambda bad - as above

2020-06-06 16:25 UTC, tomdng commented
Whoops, I've went ahead and fixed the issue for windows. Turns out there's a lot of whitespace dependent stuff I've been doing for the error checking. Now the only whitespace that the answer relies on should only be at the beginning of a line of code because of Python.

I've worked out the other issues, and since I'm planning to add the tutorial editor to Propguard, I've stopped using booleans to toggle the tutorial views and instead am using a string to select a component to display.

2020-06-06 18:41 UTC, tomdng commented
I also forgot, the hint functionality isn’t an official feature in this PR. In the future I want it to display multiple hints and have an option for filling in the answer without using a browser alert window.

2020-06-09 01:56 UTC, ClayMav approved these changes
I'd change the lambdas but it looks alright to me

2020-06-09 01:56 UTC, ClayMav commented on src/components/tutorialComponent/index.tsx
> +          clickFunction={(): void => handleStep(false)}
lambda :(

2020-06-09 01:56 UTC, ClayMav commented on src/components/tutorialComponent/index.tsx
> +          clickFunction={(): void => handleStep(true)}
lambda :(

2020-06-09 18:19 UTC, tomdng commented
Oh shoot my bad, I'll make sure to get rid of those lambda functions. Thanks for the PR review!

2020-06-16 19:27 UTC, merged